### ISSUE TITLE
Question about local point denoising

### ISSUE THREAD

**Issue by sIHURs** [PRBonn/LiDiff#18]
Hi,
First, thanks for the last reply of problem about pytroch3D install!

I would like to ask about the concept of local point denoising. How should I understand the process of constructing diffusion by adding local noise offsets to each point pm​? Why not do reparameterization at each point like DDPM does on each image (Equation 1 in the paper), but instead add noise directly to each point pm​? If possible, I would like to know how you considered this method, why it can actually work with scene data and its mathematical explanation.

Thank you!

Best regards,
Yifan

**Comment by nuneslu** [comment]
Hi! So the idea behind using diffusion over the points is mainly to avoid normalising the data, which gets a scene with 50m range and “compress” to a scene with standard deviation 1. Now during training, the model learns an approximation of the denoising process. This approximation is not perfect, therefore the final prediction has some residual noise. When training with normalised data we need to invert the normalisation, this inversion will get the “compressed” scene from standard deviation 1 back to 50m range. This inversion will also be applied to the residual noise, so the small residuals at the normalised scale will get much bigger when we get the scene back to 50m range.

Besides that, another advantage of formulating the diffusion process as a local point denoising is that the model has to learn only the points local neighbourhood distribution, instead of learning the whole scene data distribution. This makes the task easier, since modelling the local structure around one point is simpler than modelling all the different structures and objects in one scene.

Those were the main insights that we had during developing this paper, hopefully I managed to answer your question.
