### ISSUE TITLE
classfree_forward 

### ISSUE THREAD

**Issue by Mr-ZhuJun** [PRBonn/LiDiff#29]
def classfree_forward(self, x_t, x_cond, x_uncond, t):
        x_t_sparse = x_t.sparse()
        x_cond = self.forward(x_t, x_t_sparse, x_cond, t)      # 有噪声点云 x_t +  原始点x_cond    ---> nosie ：x_cond
        x_uncond = self.forward(x_t, x_t_sparse, x_uncond, t)  # 有噪声点云 x_t +  全0点x_uncond   ---> nosie ：x_uncond

        return x_uncond + self.w_uncond * (x_cond - x_uncond)

Thank you for your great work, it is very helpful，have a question.
I would like to ask why the noise of the two inferences passes through the noisy point cloud and the point cloud with all zero points. Why is there this coefficient self.w_uncond when processing？

**Comment by nuneslu** [comment]
Hi, this is for the classifier-free conditioning. Instead of using a pre-trained classifier, the classifier-free uses the conditional and unconditional distribution of the diffusion model to define the final conditioned prediction scaled by the `w_uncond` weight. You can find more information about the classifier-free conditioning in section 3.1 of our paper.
