### ISSUE TITLE
GPUs memory imbalance.

### ISSUE THREAD

**Issue by Jueqian** [PRBonn/LiDiff#35]
Hi, thanks for your great work!
During the training process, the GPU load is unbalanced. Specifically, the first GPU occupies much more memory than the others. Besides, When I use default parameters, the first GPU always over memory at the beginning of the training, until I reduced `num_points` from 180000 to 150000 that I successfully trained. Is this normal? And is there any way to optimize this?
![image](https://github.com/user-attachments/assets/86368e03-3e3b-4ef1-9566-02cc295cb35e)

**Comment by nuneslu** [comment]
Hi, this is also something we notice but as far as we know it is not related to our code. I guess it is related to pytorch lightning `ddp` multi-gpu processing or with MinkowskiEngine.

**Comment by Jueqian** [comment]
OK, thanks for your prompt reply and insights!

**Comment by nuneslu** [comment]
In case you find any solution let me know. :)

**Comment by nuneslu** [comment]
Hey! Quick update, I've found one possible solution from [here](https://github.com/pytorch/pytorch/issues/47433) which solves the problem by setting the tensor device as `device = torch.device(self.local_rank)`. Apparently, by default pytorch lightning creates the tensor on `cuda:0`, which is why one of the GPUs demands much more memory. Unfortunately, I don't have the time to try it out now, but in case this is still a problem for you, this may be a solution.
