### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by xy-cong** [PRBonn/LiDiff#5]
Dear authors,

I'm curious about whether it is possible to be trained on other datasets, such as nuScenes/Waymo. Have you ever tried that?

Thanks.

**Comment by nuneslu** [comment]
Hi, we haven't tried, for nuScenes semantic labels are not available for all the scans, therefore we could not remove the moving objects to train the model in a "clean data". For waymo we haven't tried because the dataset is too large. However, for both datasets it should be possible to train the model and achieve scene completion as long as one is able to clean the data.

**Comment by nuneslu** [comment]
I will close this issue now but feel free to reopen it or create a new one if have more questions. :)
